### ISSUE TITLE
[Documentation] Add a section in README.md about how to build a unity package form source

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1014]
## Description
 
Add a section in README.md about how to build a unity package form source.

## Additional info

This request comes from the fact that a lot of users didn't know how to do it and asked us how to build a unity package.

**Comment by SandyEma9** [comment]
@sandraaltom in which README.md should be better?General one or the one from Docs?

**Comment by sandraaltom** [comment]
@SandyEma9 I'm thinking that in the README.md of the repository.

**Comment by iulianatodoran** [comment]
✔️ Checked the `README.md` for the repo for AltTester Unity SDK  file and the correct and complete information is present in order to inform users how to build a unity package form source.

![image](https://user-images.githubusercontent.com/62327834/207614776-9a95fd74-e19c-4a58-9962-df0e08fc8491.png)

Closing the ticket.
