### ISSUE TITLE
Add ability to switch from custom input to normal input in instrumented builds

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1041]
**Describe the feature/enhancement**

There are 2 things to do in this ticket.
1. A way to switch to use normal input(input from keyboard and mouse) to our custom input.
2. Have a way for user to see what input is active in the instrumented build.

(Select which label is suitable for your issue)
/label ~feature  /label ~enhancement

**Comment by iulianatodoran** [comment]
### Testing Environment
- OS for creating builds: Windows 11/ MacOS Big Sur v 11.7.2
- Unity versions: v 2021.3.5f1 (for Android build from MacOS), v 2021.3.16f1 (for Standalone from Windows)
- AltTester Unity SDK v 1.8.2 from `development` branch (27.01.23)
- AltTester Desktop v 1.5.1 (released)

### Tests performed and results
- ✅ Checked that the `AltTesterRunnerPrefab` in the instrumented build has a toggle for `Custom Input` to uncheck/check in order to use normal input (unchecked) or custom input (checked)
     ![image](https://user-images.githubusercontent.com/62327834/215080435-572a38bc-3a13-45a4-a42e-7a84c867538c.png)
- ✅ Checked that when the `Custom Input` toggle is checked the `AltTesterRunnerPrefab` prefab is colored in green
      ![image](https://user-images.githubusercontent.com/62327834/215080321-70fa2d56-8007-4f39-afb7-0705faef41e8.png)
- ✅ Checked that when the `Custom Input` toggle is unchecked the `AltTesterRunnerPrefab` prefab is colored in blue
      ![image](https://user-images.githubusercontent.com/62327834/215080182-4a016c0d-8621-4662-8cf5-d1b80ebea8fa.png)
- ✅ Checked that by default the `Custom Input` toggle is checked (every time the AltTester is connected the first time or after a disconnection)
- ✅ Checked with the game connected to AltTester Desktop while the `Custom Input` toggle is unchecked that  the regular input (from keyboard/mouse) can be used in the game build and the simulated input in AltTester Desktop or automated tests will not work
- ✅ Checked with the game connected to AltTester Desktop while the `Custom Input` toggle is checked for scenes that use the old Input system that the regular input (eg from the keyboard) cannot be used in the game build, and the simulated input in AltTester Desktop or automated tests will work
  - _Note_: in the Input System (New) scenes the user cannot interact at all with the game only through AltTester Desktop or automated tests
- ✅ Checked that while running automated tests the` Custom Input` is active all the time, no matter the setting from the toggle in the game
- ✅ Checked in the generated HTML build for documentation that in the _Advanced Usage_ section, the complete and correct information is included, with no UI/layout issues
![image](https://user-images.githubusercontent.com/62327834/215108517-ea7f0a5e-33af-4fa3-af63-2fd4e877bd47.png)
    - _Note_: could not yet check the new included information on the Staging docs while there is another pipeline issue that needs to be fixed, but before the release will recheck the documentation to have included all the necessary information

### Notes
- some small issues observed during testing will be treated in different tickets (https://github.com/alttester/AltTester-Unity-SDK/issues/1080 and https://github.com/alttester/AltTester-Unity-SDK/issues/1073)

### Conclusions
- the purpose of this ticket was achieved

**Closing the ticket.**
