### ISSUE TITLE
CheckDesktopVersionRequest  - Add validation for regex match

### ISSUE THREAD

**Issue by alexrotaru** [alttester/AltTester-Unity-SDK#1048]
For users on Linux an exception is thrown when checking for a new version. 
adding a check (if (regex is not null) ) before doing the regex.Match() will help. 

_From Shaun The Sheep on Discord (https://discord.com/channels/744769398023127102/1062648440334589952)_

**Comment by iulianatodoran** [comment]
### Testing environment
- Unity v `2021.3.16f1` (Windows 11/MacOs Big Sur 11.7.2), `2021.3.15f1` (Linux: Ubuntu  22.04.1 LTS)
- AltTester Unity SDK from `development` branch from 31.01.23

### Tests performed and results
- ✅ Checked in Unity in the _Altester Editor_ window on Windows and MacOS that the popup for AltTester Desktop new version release is displayed when a new version of AltTester Desktop is released
- ✅ Checked in Unity in the _Altester Editor_ window on Windows and MacOS that after the new version popup is closed it is not displayed anymore until a newer version is released for AltTester Desktop
- ✅ Checked in Unity in the _Altester Editor_ window on Linux that no popup new version release is displayed and no errors are triggered in the console 

### Conclusions
- The purpose of this ticket was achieved: the issue is fixed

**Closing the ticket**.
