### ISSUE TITLE
Keep Define setting is not checked when switching the platform.

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1075]
## Steps to reproduce
 
1. Check that the platform(1) you want to test doesn't have the define
2. Switch to another platform(2)
3. Check the Keep ALTTESTER Define toggle
4. Switch back to the platform(1) you want to check
5. Check in Player Settings if the define is visible

Don't select for Platform(1) or (2) the Editor option. Other options are ok

### AR
 
Define is not visible.

## Expected result
Define should be visible.

**Comment by iulianatodoran** [comment]
### Testing environment
- Unity v `2021.3.16f1` (Windows 11/MacOs Big Sur 11.7.2)
- AltTester Unity SDK from `development` branch from 31.01.23

### Tests performed and results
- ✅ Checked in Unity in the _Altester Editor_ window that by following the steps described in the ticket the expected result is achieved: the `ALTTESTER` define symbol is visible in _Project Settings_ > _Player_ > _Other_ > _Scripting Define Symbols_
- ✅ Checked that by switching back to platform(2) the `ALTTESTER` define symbol is still visible in _Project Settings_ > _Player_ > _Other_ > _Scripting Define Symbols_
- ✅ Checked that when the setting for the `ALTTESTER` symbol is checked in _Build Settings_ the Editor does not take a long time to compile adding/removing the symbol every time the Playmode is started/stopped or a test script is modified
- ✅ Checked in the _Altester Editor_ window that all the other functionalities still work as expected and the correct settings are displayed for each selected platform
- ✅ Checked in Unity in the _Altester Editor_ window that there are no UI/Layout related issues after the tix

### Conclusions
- The purpose of this ticket was achieved: the issue is fixed

**Closing the ticket**.
