### ISSUE TITLE
[Legal] Compliance with the "Package" requirements implied in the Unity Editor Software Terms & UPM Guidelines

### ISSUE THREAD

**Issue by sandraaltom** [alttester/AltTester-Unity-SDK#1159]
We should make sure that in order to make our sdk a package, we comply with the "Package" requirements from the Unity Editor Software Terms & UPM Guidelines.

## Description
 

- we should comply with the "Package" definition

> In the [Unity Software Terms](https://docs.google.com/document/d/16cI3glgrKW3yLgrmPL88HUmGDnM4K7ERKjEt7eBet-g/edit#), a “Package” means a distribution of files or resources packed together as a software collection to provide certain functionality to Unity Software users. 

- we should not make reference to the Inspector from the AltTester Editor

> In the [UPM Guidelines](https://docs.google.com/document/d/10fI5jUHlYfWRY-6uctwz1bOZyLoZyXY6AN5Gs_B2K90/edit), `Safety` is defined as: `We will protect our community from being misled by unauthorized vendors who are using the editor as a marketing channel. `

- we should not use the Editor as a marketing / distribution package (e.g. we are not allowed to promote other services)

> The [UPM Guidelines](https://docs.google.com/document/d/10fI5jUHlYfWRY-6uctwz1bOZyLoZyXY6AN5Gs_B2K90/edit) states that: `You cannot make any Package (including via Package update) available from within the Unity Editor to third parties (other than your Designated Users) that, directly or indirectly, advances or is intended to advance the commercial or economic interests of you and/or your affiliated entities.  For example: A Package that induces a person to buy or subscribe to products or services.`

- we should make sure that our sdk is not collecting data, when it is available from Unity Editor to third parties 

> `You cannot make any Package (including via Package update) available from within the Unity Editor to third parties (other than your Designated Users) if such Package provides a service that collects or aggregates data. For example:
A Package that enables a third party analytics service.`

> Note: We are currently collecting data, but with the purpose of understanding how is the AltTester Editor used

- we should make sure that we are not auto-updating our sdk 

> `You cannot harm or mislead users. You cannot add, update or modify installed Packages on behalf of the user outside the official Unity Editor UI, such as programmatically through scripts.`

- we should not force our users to install New Input System 

> `Your Package cannot require arbitrary or unnecessary dependencies to install an additional Package.`

- we should make sure that we do not change project settings / content without user's permission (if we do, then we need another ticket to implement the request for permission)
> `Your Package cannot change project settings or Project Content without a user’s opt-in authorization.`

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows `11`
- `AltTester Unity SDK` from `development` branch (20.04.2023)
- Unity version `2021.3.16f1 LTS`

### Tests performed and results
- ✅Checked that the unity package complies with the "Package" definition and its scripts contain namespaces that comply with the [UPM Guidelines](https://docs.google.com/document/d/10fI5jUHlYfWRY-6uctwz1bOZyLoZyXY6AN5Gs_B2K90/edit)
- ✅Checked that the AltTester Desktop is not mentioned in the AltTester Editor (in popups), in the top menu, or in any files from the Unity package
- ✅Checked that `altom.com` is not mentioned anywhere in the files from the unity package except the LICENSE and Google group address
    - ❌ issue found: for a mention that should not happen opened https://github.com/alttester/AltTester-Unity-SDK/issues/1214
- ✅Confirmed that we are not auto-updating our SDK (and it never did)
- ✅Checked that we are not forcing our users to install the New Input System, so that when an empty project is created and the unity package imported no errors regarding New Input System are present in the console
- ✅Checked that in the _AltTester Editor_ window, there is a message about building or playing in Editor that adds the ALTTESTER define symbol
    ![image](https://user-images.githubusercontent.com/62327834/233400209-e830bdc6-5a42-47d9-bdb6-4ffd2f24038a.png)

### Conclusion
The purpose of this ticket was achieved.

**Closing the ticket.**
