### ISSUE TITLE
[AltTester Editor] 'UnauthorizedAccessException' when XML file path points to a folder

### ISSUE THREAD

**Issue by ralupopa** [alttester/AltTester-Unity-SDK#1195]
**In what language is the test written?** 
C#

**What version of Unity are you using?**
2021.3.12f1

**What version of AltTester Unity SDK are you using?**
1.8.0 or 1.8.1

**The OS from where you are running the test?**
Windows

### Summary

When a specific xml file name is not provided in 'XML file path' error 'UnauthorizedAccessException: Access to the path '...' is denied.'

### Steps to reproduce

1. Have tests prepared to be executed in Unity Editor using AltTester Editor.
2. Check 'Create XML Report' from Test Run Settings
3. Provide XML file path to a folder, not a file with xml extension.

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/62647565/229800836-98b60b20-8f8a-4377-a12e-9df43a57b1c1.png)

Seems that https://github.com/alttester/AltTester-Unity-SDK/blob/development/Assets/AltTester/Editor/AltTestRunner.cs#L624 takes that path and tries to create an xml or write if the file exists.

### Wanted
Rather improvement than bug: in case a `<file_name.xml>` is not provided in path, create a file with a default name.
When using dotnet CLI for running tests which use NUnit the XML result report default is TestResult.xml, so a similar behavior would be nice.

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.6
- builds instrumented with SDK: 
  - SampleScenes with SDK on `development` branch (16.06.23) opened in Unity 2021.3.16f1 on MacOS
  - RolABall with SDK on `development` branch (16.06.23) opened in Unity 2022.3.2f1 (LTS) on Windows
- AltServer started from AltTester Desktop v.2.0.0

### Tests performed and results
- Checked that when the `Create XML Report` option is selected
  - ✅after not providing a file name and no folder location to the XML file path a default result report `test-report.xml` is generated in the parent folder of the project and there are no errors in the console
  - ✅after not providing a file name, but a folder location to the XML file path a default result report `test-report.xml` is generated in the folder provided in the path and there are no errors in the console
  - ✅after providing a file name but no folder location to the XML file path a result report with the provided name` is generated in the parent folder of the project and there are no errors in the console
  - ✅after providing a file name and a folder location to the XML file path a result report with the provided name` is generated in the provided folder of the project and there are no errors in the console
- ✅Checked that when the `Create XML Report` option is not selected no result report is generated in the project parent folder and there are no errors in the console
- ✅Checked that after running tests with the `Create XML Report` option selected, the `Test Report` pop-up is displayed at the end of the run in the Unity window
- ✅Checked that there are no GUI/layout/functionality issues on the AltTester Editor window and everything is functional
- ✅Checked that there are no play mode issues or test running issues

### Conclusions
The issue was fixed and improvements were implemented with the expected behaviors. No other issues were found during the testing of this ticket.

**Closing the ticket.**
