### ISSUE TITLE
Create an example and test input with InputSystem.OnScreen.OnScreenStick.html

### ISSUE THREAD

**Issue by rucindrea** [alttester/AltTester-Unity-SDK#1287]
From one of our users, we learned that the On Screen Stick input isn't working properly with our Custom Input (de-seelcting the AltTester input on the dialog in the game doesn't allow user to use the joystick normally). 

https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.OnScreen.OnScreenStick.html

We should have an example with this kind of controls and test it with the AltTester input.

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 10, MacOS Big Sur 11.7.7
- AltTester Desktop from `development` branch (02.08.2023) 
- _Samplegame_ iOS instrumented with AltTester Unity SDK v 2.0.1 from `development` branch (03.08.2023)

### Tests performed and results
- ✅ Checked that when the instrumented game is not connected to the AltTester Desktop (with `Custom Input` deselected in the game's green popup) in `Scene 10` the two buttons created for the example work as expected 
- ✅ Checked that when the instrumented game is connected to the AltTester Desktop (with `Custom Input` selected in the game's green popup) in `Scene 10` the two buttons created for the example work as expected using the `Click/Press` and `Tap/Swipe` actions in the Screenshot Area
- ✅ Checked that in the AltTester Desktop's Recorder the above-mentioned actions are recorded as expected on the 2 buttons from `Scene 10`
- ✅ Checked that the test created for this ticket runs successfully on the iOS instrumented app
  - ❌ there is a mistake in the test as in line 367 of the `TestOnScreenInput()` test (`TestForNIS.cs`) the object to find is named `Button` instead of `Stick` so I replaced with the correct value and the test passed
    ![image](https://github.com/alttester/AltTester-Unity-SDK/assets/62327834/e6f99723-b175-42f4-9498-74c4eaf6beea)

- ✅ Checked in the other scenes that the input behaves as expected both for `Custom Input` selected/deselected the game's green popup

### Issues found during testing
- the test script mistake mentioned above will be fixed in one of @RobertPoienar PRs and he will notify me to recheck it

### Notes on testing
- The iOS platform was tested in this ticket, Windows/MacOS/Android platforms were already verified in the implementation phase

### Conclusion
The purpose of this ticket was achieved. The small test issue will be fixed separately

**Closing the ticket.**
