### ISSUE TITLE
[EditorWindow] Play in editor not working without having "Keep ALTTESTER define on"

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1296]
## Steps to reproduce
 
1. Open editor window
2. Uncheck Keep AltTester define On
3. Press Play in Editor

## Actual result

Build Interrupted error appears and doesn't start playing.
## Expected result

Application starts playing in editor

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.6
- builds instrumented with SDK: 
  - SampleScenes with SDK on `development` branch opened in Unity 2021.3.16f1 on MacOS
  - TrashCat with SDK on `development` branch opened in Unity 2021.3.16f1 on MacOS
  - Karting game from Unity samples with SDK package imported in project, opened n Unity 2021.3.25f1 (LTS)
- AltServer started from batchmode from AltTester Desktop v.2.0.0

### Tests performed and results
- ✅Checked that in the AltTester Editor window the play mode can be started successfully with no error in the console when the `Keep ALTTESTER symbol defined` is unchecked
- ✅Checked that in the AltTester Editor window the play mode can be started successfully with no error in the console when the `Keep ALTTESTER symbol defined` is checked
- ✅Checked that while in playmode the build can connect with AltServer successfully
- ✅Checked that can create an instrumented build from the AltTester Editor window when the `Keep ALTTESTER symbol defined` is unchecked
- ✅Checked that can create an instrumented build from the AltTester Editor window when the `Keep ALTTESTER symbol defined` is checked
- ✅Checked that there are no GUI or layout issues on the AltTester Editor window and everything is functional

### Conclusions
The issue was fixed. No other issues were found during the testing of this ticket.

**Closing the ticket.**
