### ISSUE TITLE
[EditorWindow] AltTesterEditor.asset file is not created when SDK is imported as package

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1297]
## Steps to reproduce
 
1. Import SDK from OpenUPM
2. Open Editor window
3. Try do some action with it

## Actual result
Editor Window is not working

## Expected result
Editor Windows functionality should work

## Testability

For Testing: make sure that configurationFile is created without any errors and that EditorWindows works even if you move the file to another path. 

Also this can be tested once we have a prerelease that is added to OpenUPM

**Comment by iulianatodoran** [comment]
Waiting for a pre-release tag to be uploaded on OpenUPM in order to test this ticket.

Source for package: https://openupm.com/packages/com.alttester.sdk/

**Comment by iulianatodoran** [comment]
### Testing environment
- OS: Windows 11, MacOS Big Sur v 11.7.7
- Unity Editor versions: 2022.3.4.f1 (Windows), 2021.3.16f1 (MacOS)
- AltTester Unity SDK version 2.0.1-alpha2 (special package uploaded on UPM)
- AltTester Desktop version 2.0.1 pre-release build from `development` branch on 28.06.23

### Tests performed and results
- ✅ Checked that by following the steps from the ticket there are no problems in the AltTester Editor window and the `Play in Editor` behaves as expected
- ✅ Checked that a connection with the AltServer and AltTester Desktop is possible while playing in AltTester editor
- ✅ Checked that there are no errors in the Unity console related to the `AltTesterEditorSettings.asset` (the configurationFile mentioned in the Testability section of the ticket)
- ✅ Checked that there are no errors in the Unity console related to the `manifest.json` meta file
- ✅ Checked that by moving the `AltTesterEditorSettings.asset file to another location there are still no errors in the Unity console and playing in editor has the expected behavior

### Conclusion
The issue is fixed.

**Closing the ticket.**
