### ISSUE TITLE
"The type or namespace name 'InputTestFixture' could not be found error" is triggered when try to create a build in Unity Project with addressable

### ISSUE THREAD

**Issue by MihaiCuc98** [alttester/AltTester-Unity-SDK#1373]
## Steps to reproduce
1. Create a unity project in 2021.3 or older
2. Add _AltTester_, _NewInputSystem_ and _Addresables_ packages
3. Create an _Addressables_
4. Make sure the project is set to use _NewInputSystem_ or both systems and have an _Addresable_ created
5. In _Addressables Groups_ try to build an `Default Build Script` and from the AltTester Editor try to create an instrumented build

I attached a sample project where this problem is reproducible
[AltTesterAddressablesProblem.zip](https://github.com/alttester/AltTester-Unity-SDK/files/12724531/AltTesterAddressablesProblem.zip)
 

### AR
The` type or namespace name 'InputTestFixture' could not be found (are you missing a using directive or an assembly reference?)` error is triggered when trying to build an `Default Build Script` and the instrumented build cannot be created

 

### 

Additional info
Related threads:
- https://discord.com/channels/744769398023127102/744769398497214614/1136683481125109790
- https://discord.com/channels/744769398023127102/748145712100933682/1142123805511274499
- https://discord.com/channels/744769398023127102/1144016659514937405
- https://discord.com/channels/744769398023127102/748145712100933682/1144557304558137424

**AltTester Version:** 2.0.2
 

### ER
 
No errors should be triggered when the instrumented build is created **with the condition** that the `Keep ALTTESTER symbol definded` option is unchecked when trying to build an `Default Build Script` from _Addressables_
  - This condition shoud be mentioned in the documentation for the build process to work (along with the necessary step of creating the `Default Build Script` from _Addressables_)

**Comment by iulianatodoran** [comment]
### Testing environment
- Unity v 2021.3.16f1, 2022.3.8f1
- Roll-a-ball game (NIS) instrumented with AltTester Unity SDK v >2.0.2 from `development` branch (09.10.23)

### Tests performed and results
- ✅ Checked in the provided sample project (using  _AltTester_, _NewInputSystem_ and _Addresables_ packages) that I am able to instrument a build with no errors (with or without the `Keep the ALTTESTER symbol defined` option checked)
- ✅ Checked that the previously instrumented build can connect successfully to AltTServer and to the AltTester Desktop
- ✅ Checked that I am able to build an `Default Build Script` from Addressables prior to instrumenting the build with AltTester Unity SDK only when the `Keep the ALTTESTER symbol defined` option is checked
- ✅ Checked also that playing in the AltTester Editor window (with or without the `Keep the ALTTESTER symbol defined` option checked) works as expected with no errors in the unity console

### Issues found during testing
- ❌ For a build created in Unity `2022.3.8f1` the green panel that opens from the green popup is not interractable - this issue is still investigated if it is related to the fix or not > will come back later to update the information
- ❌ the documentation does not contain information about the condition mentioned in the **Expected result** for  building the instrumented build when Addressables package is included and used in the project 

### Conclusion
For the second issue mentioned above will reopen the ticket.

**Comment by RobertPoienar** [comment]
The issue with `Unity 2022` is not related with Addressable, it was simply because the scene that it was tested didn't contained an event system, so I will not fixed that issue. But I will add the documentation.

**Comment by MihaiCuc98** [comment]
### Additional check:
✔ Checked if no errors are triggered when a build without Addresabbles is made (Standalone, Android, Play in Editor) (`Editor|ERROR|System.NullReferenceException: Object reference not set to an instance of an object` was triggered in the past in the SDK project so this is the purpose of this check)

### Setup:
- Windows 10 
- AltTester Unity SDK project with latest changes from dev (11.10.2023 - 16:10)
- Empty 2d game project where a unity package (created from the project above) was added
- Goal Keeper instrumented with the latest AltTester Unity SDK from dev branch(11.10.2023 - 16:10)

**Comment by iulianatodoran** [comment]
### Additional testing performed
✅ Checked in the Staging documentation in the _FAQ_ > _Troubleshooting_ area that the required correct and complete information is included as requested in the ticket's **Expected result** with no typos or layout issues

### Conclusion
Considering this and what was tested before as seen in the previous comments, **will close this issue**.
