### ISSUE TITLE
[Input] Tap is not working when running the game in UnityEditor - batchmode

### ISSUE THREAD

**Issue by RobertPoienar** [alttester/AltTester-Unity-SDK#1466]
Any Input commands that uses WaitForEndOfFrame suffers from this. More info why this is not working in Editor batchmode can be found here: https://docs.unity3d.com/Manual/CLIBatchmodeCoroutines.html

## Steps to reproduce
 
1. Run instrumented application in editor batchmode
2. Run a test that uses tap

### AR
 
Commands is stuck and the test will throw timeout exception

### ER
 
Tap command to be successful

**Comment by MihaiCuc98** [comment]
### Testing setup:
- Windows10
- AltTesterDesktop made from the dev branch (17.01.2024)
- AltTester-Unity-SDK project (latest dev branch 17.01.2024)
- SampleScenes game run in batchmode
- User demo project

### Checks:

✔ Checked if the scenario is no longer reproducible using the user's demo project (tested with Python, c#)
❌ Check if the bindings (c#, python, java) are successfully run using the SampleScenes game in batchmode:
- dotnet - 30 failed tests
- python: test_multipoint_swipe_NIS
- java: :heavy_check_mark:

greed with the team that this behavior has been tested enough because it is an edge case. Considering this information, I will move this ticket into `Done`.
