### ISSUE TITLE
[Bindings] 60s retry timeout for connecting Python and Java tests 

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/AltTester-Unity-SDK#1477]
## Description
We should have consistency in Bindings on how the tests connect to the AltServer , so the Python and Java bindings should have the same connection retry timeout of  60s.

### Additional info
- issue found while testing https://github.com/alttester/AltServer/issues/62

**Comment by iulianatodoran** [comment]
Triaged Week no.3.

**Comment by andreion1ca** [comment]
At the moment, we have consistency in Bindings on how the tests connect to the AltServer. The Python, Java, and .NET bindings have the same connection retry timeout of 100 millis. The problem comes from .NET where the disconnect takes 5 seconds, so the reconnect can't be made every 100 millis. Closing this ticket.
