### ISSUE TITLE
Test results are always false. It looks like altDriver object was not created 

### ISSUE THREAD

**Issue by Stas-Udod** [alttester/AltTester-Unity-SDK#1483]
**In what language is the test written?** 
C#

**What version of Unity are you using?**
2022.3.17f1

**What version of AltTester® Unity SDK are you using?**
2.0.3

**On what device are you trying to run the test?**
Unity Editor

**The OS from where you are running the test?**
Windows 11

### Summary
Test results are always false. 
I'm using the Community version. Tests always pass failed. It looks like the object is not being created in "altDriver =new AltDriver();" clause

### Steps to reproduce
1. As described in the “Get started” documentation, I opened the "TrashCat" example, imported AltTester, specified Dependencies, and instrumented.
2. Created 1 test that outputs a message to the console. And in the SetUp() method I set the message output to the console
[OneTimeSetUp]
public void SetUp() {
        NLog.Logger logger = EditorLogManager.Instance.GetCurrentClassLogger();
        logger.Info("Point 1");
        altDriver = new AltDriver();
        logger.Info("Point 2"); // <------ This message has never been shown in Console!
}
3. Launched AltTester Desktop, launched the application from the Unity editor. The connection is established and the properties are displayed.
4. In AltTester Editor I mark the test and do Run Selected Tests.
The "Point 1" entry appears in the console, then some number pairs of "DEBUG|Driver Connected <ID>" and "DEBUG|Driver Disconnect <ID>" entries. Then the "Test report" modal window appears in which says that all tests failed, and in the console the error message "Editor|ERROR|OneTimeSetUp: AltTester.AltTesterUnitySDK.Driver.MultipleDriversException : Multiple drivers detected. Free accounts are limited to a single driver connection at a time". The "Point 2" message is not shown in the console at all.

Please help me how to pass the tests. I don't want use Multiple Drivers.

### Relevant logs and/or screenshots
![image](https://github.com/alttester/AltTester-Unity-SDK/assets/108701321/c35ba4b1-9133-40cd-b859-12658fc79011)

**Comment by iulianatodoran** [comment]
@Stas-Udod, if you use the Community Edition for AltTester Desktop you can't inspect the game and connect the tests simultaneously. If you want to run the tests you only need to open AltTester Desktop so that the AltServer connection can be created, but do not use the `Inspect App` button. Also, when you want to inspect the game only, then you should not run tests simultaneously.
If you want to do both simultaneously then you may purchase the PRO edition of the AltTester Desktop.

Let us know if you manage to run the tests successfully after this follow-up so we can close this ticket.

**Comment by Stas-Udod** [comment]
Iulianatodoran, thank you very much for your detailed explanations! It helped. Tests are going well.
