### ISSUE TITLE
Add documentation for 2.1

### ISSUE THREAD

**Issue by gomboskriszta15** [alttester/AltTester-Unity-SDK#1542]

**Comment by iulianatodoran** [comment]
### Testing environment
- Staging documentation for AltTester Unity SDK project

### Checks
- ✅ Robot Framework added in all places where the other bindings are mentioned, except the examples and API (which will be handled after the 2.1 release)
- ✅ Updates in _Overview_ > _Key features_ with Robot Framework and concurrent testing on multiple devices
- ✅ Update in _Overview_'s first screenshot with Robot Framework logo
- ✅ Update for `newtonsoft-json` 's version in _Get Started_ > _Import AltTester package in Unity Editor_ > _Resolve dependencies_
- ✅ Update in _AltTester Editor_ > _Build Settings_ for the second screenshot with the latest version green popup
- ✅ Note added in _Advanced Usage_ > _Execute tests concurrently_ for adding different product names in case users start multiple instrumented apps on the same device, otherwise their tests might fail because they are using the same resources (ex. values saved to PlayerPref). 
- ✅ Updates in _Known Issues_ with the `2.x` version
- ✅ Updates for the new release made before this ticket are still correct and complete
- ✅ No layout issue, typos, missing sections

### Conclusion
Considering the above information **I will move this ticket to `Done`**.
